inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - 'Gemfile'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'app/helpers/application_helper.rb'
    - 'app/models/application_record.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes
